export const AUDIT_ENDPOINTS = {
  audits: '/api/v1/audits',
  audit: (id: string) => `/api/v1/audits/${id}`,
  start: (id: string) => `/api/v1/audits/${id}/start`,
  pause: (id: string) => `/api/v1/audits/${id}/pause`,
  resume: (id: string) => `/api/v1/audits/${id}/resume`,
  saveDraft: (id: string) => `/api/v1/audits/${id}/save-draft`,
  complete: (id: string) => `/api/v1/audits/${id}/complete`,
  cancel: (id: string) => `/api/v1/audits/${id}/cancel`,
  reopen: (id: string) => `/api/v1/audits/${id}/reopen`,
  clone: (id: string) => `/api/v1/audits/${id}/clone`,
  observations: (id: string) => `/api/v1/audits/${id}/observations`,
  findings: (id: string) => `/api/v1/audits/${id}/findings`,
  evidence: (id: string) => `/api/v1/audits/${id}/evidence`,
  interviews: (id: string) => `/api/v1/audits/${id}/interviews`,
  signatures: (id: string) => `/api/v1/audits/${id}/signatures`,
  calendar: (id: string) => `/api/v1/audits/${id}/calendar`,
  reminders: (id: string) => `/api/v1/audits/${id}/reminders`,
};
