'use client';

import type { ReactNode } from 'react';

import { ProtectedRoute } from '@/components/guards/RouteGuard.js';
import { DashboardNav } from '@/components/layouts/DashboardNav.js';
import { Breadcrumbs } from '@/components/layouts/Breadcrumbs.js';
import { usePathname } from 'next/navigation';

const PATH_LABELS: Record<string, string> = {
  '/dashboard': 'Overview',
  '/executive': 'Executive Dashboard',
  '/search': 'Global Search',
  '/worker-voice': 'Worker Voice',
  '/worker-voice/my-cases': 'My Cases',
  '/worker-voice/report': 'Report Concern',
  '/worker-voice/hotline': 'Ethics Hotline',
  '/worker-voice/ai-assistant': 'AI Worker Assistant',
  '/worker-voice/knowledge-center': 'Knowledge Center',
  '/worker-voice/emergency-help': 'Emergency Help',
  '/worker-communication': 'Worker Communication',
  '/worker-ai': 'AI Worker Assistant',
  '/worker-ai/documents': 'Documents',
  '/worker-ai/emergency': 'Emergency',
  '/worker-ai/rights': 'Rights',
  '/worker-ai/training': 'Training',
  '/workers': 'Workers',
  '/workers/overview': 'Overview',
  '/workers/profile': 'Profile',
  '/workers/directory': 'Directory',
  '/workers/announcements': 'Announcements',
  '/workers/tasks': 'Tasks',
  '/workers/documents': 'Documents',
  '/workers/forms': 'Forms',
  '/workers/learning': 'Learning',
  '/workers/support': 'Support',
  '/workers/settings': 'Settings',
  '/workers/engagement': 'Engagement',
  '/workers/engagement/surveys': 'Surveys',
  '/workers/engagement/surveys/builder': 'Survey Builder',
  '/workers/engagement/surveys/[id]': 'Survey',
  '/workers/engagement/surveys/analytics': 'Survey Analytics',
  '/workers/engagement/recognition': 'Recognition',
  '/workers/engagement/recognition/leaderboard': 'Leaderboard',
  '/workers/engagement/recognition/history': 'History',
  '/workers/engagement/wellbeing': 'Wellbeing',
  '/workers/engagement/wellbeing/checkin': 'Check-in',
  '/workers/engagement/wellbeing/tips': 'Tips & Resources',
  '/workers/engagement/goals': 'Goals',
  '/workers/engagement/community': 'Community',
  '/workers/engagement/community/[id]': 'Community',
  '/workers/engagement/events': 'Events',
  '/workers/engagement/events/[id]': 'Event',
  '/workers/engagement/ai-insights': 'AI Insights',
  '/workers/engagement/manager': 'Manager Dashboard',
  '/workers/engagement/analytics': 'Analytics',
  '/assessments': 'Assessments',
  '/assessments/templates': 'Templates',
  '/assessments/templates/[id]': 'Template',
  '/assessments/templates/[id]/versions': 'Versions',
  '/assessments/library/[id]': 'Library',
  '/standards': 'Standards',
  '/standards/[id]': 'Standard',
  '/standards/frameworks/[id]': 'Framework',
  '/audits': 'Audits',
  '/audits/[id]': 'Audit',
  '/admin/cases': 'Cases',
  '/admin/cases/[id]': 'Case',
  '/capa': 'Findings & CAPA',
  '/escalation': 'Escalation',
  '/grievances': 'Grievances',
  '/admin/grievances': 'Grievances',
  '/admin/grievances/categories': 'Categories',
  '/admin/grievances/portal-config': 'Portal Config',
  '/admin/grievances/qr-portals': 'QR Portals',
  '/track-grievance': 'Track Grievance',
  '/compliance-score': 'Compliance Score',
  '/ai': 'AI Compliance Copilot',
  '/ai/overview': 'Overview',
  '/ai/chat': 'Ask AI',
  '/ai/document-ai': 'Document Intelligence',
  '/ai/knowledge-base': 'Knowledge Base',
  '/ai/policy-generator': 'Policy Assistant',
  '/ai/audit-assistant': 'Audit Assistant',
  '/ai/predictive': 'Risk Advisor',
  '/ai/autonomous': 'Workflow Builder',
  '/ai/analytics': 'Analytics',
  '/ai/clause-explorer': 'Clause Explorer',
  '/ai/conversations': 'Conversations',
  '/ai/settings': 'Settings',
  '/dashboard/sustainability': 'Sustainability',
  '/dashboard/sustainability/programs': 'Programs',
  '/dashboard/sustainability/programs/new': 'New Program',
  '/dashboard/sustainability/programs/[id]': 'Program',
  '/dashboard/sustainability/goals': 'ESG Goals',
  '/dashboard/sustainability/goals/new': 'New Goal',
  '/dashboard/sustainability/goals/[id]': 'Goal',
  '/dashboard/sustainability/kpis': 'KPIs',
  '/dashboard/sustainability/kpis/new': 'New KPI',
  '/dashboard/sustainability/kpis/[id]': 'KPI',
  '/dashboard/sustainability/initiatives': 'Initiatives',
  '/dashboard/sustainability/initiatives/new': 'New Initiative',
  '/dashboard/sustainability/initiatives/[id]': 'Initiative',
  '/dashboard/sustainability/reports': 'Reports',
  '/dashboard/sustainability/reports/new': 'New Report',
  '/dashboard/sustainability/reports/[id]': 'Report',
  '/dashboard/sustainability/settings': 'Settings',
  '/dashboard/carbon': 'Carbon & GHG',
  '/dashboard/carbon/dashboard': 'Dashboard',
  '/dashboard/carbon/facilities': 'Facilities',
  '/dashboard/carbon/emission-sources': 'Emission Sources',
  '/dashboard/carbon/scopes': 'GHG Scopes',
  '/dashboard/carbon/emissions': 'Emissions',
  '/dashboard/carbon/emission-factors': 'Emission Factors',
  '/dashboard/carbon/projects': 'Reduction Projects',
  '/dashboard/carbon/offsets': 'Carbon Offsets',
  '/dashboard/carbon/targets': 'Reduction Targets',
  '/dashboard/carbon/reports': 'Carbon Reports',
  '/dashboard/carbon/calculator': 'Calculator',
  '/dashboard/environment': 'Environmental',
  '/dashboard/environment/air': 'Air',
  '/dashboard/environment/chemicals': 'Chemicals',
  '/dashboard/environment/incidents': 'Incidents',
  '/dashboard/environment/permits': 'Permits',
  '/dashboard/environment/projects': 'Biodiversity',
  '/dashboard/environment/resources': 'Resources',
  '/dashboard/environment/risks': 'Risk Register',
  '/dashboard/environment/settings': 'EMS Settings',
  '/dashboard/environment/waste': 'Waste',
  '/dashboard/environment/water': 'Water',
  '/dashboard/esg': 'ESG Reporting',
  '/dashboard/esg/frameworks': 'Frameworks',
  '/dashboard/esg/metrics': 'Metrics',
  '/dashboard/esg/periods': 'Periods',
  '/dashboard/esg/disclosures': 'Disclosures',
  '/dashboard/esg/reports': 'ESG Reports',
  '/dashboard/esg/materiality': 'Materiality',
  '/dashboard/esg/assurance': 'Assurance',
  '/dashboard/esg/data-points': 'Data Points',
  '/analytics': 'Compliance Analytics',
  '/reports': 'Compliance Reports',
  '/admin/users': 'Users',
  '/admin/organizations': 'Organizations',
  '/admin/sites': 'Sites',
  '/admin/roles': 'Roles & Permissions',
  '/admin/audit': 'Audit Trail',
  '/admin/security': 'Security Review',
  '/admin/ai': 'AI Foundation',
  '/risk': 'Risk',
  '/factory': 'Factories',
  '/supplier': 'Suppliers',
  '/supplier-audits': 'Supplier Audits',
  '/supplier-carbon': 'Supplier Carbon',
  '/supplier-esg': 'Supplier ESG',
  '/supplier-risk': 'Supplier Risk',
  '/supplier-scorecards': 'Supplier Scorecards',
  '/responsible-sourcing': 'Responsible Sourcing',
  '/certifications': 'Certifications',
  '/qr-codes': 'QR Codes',
  '/qr-codes/[id]': 'QR Code',
  '/communication-hub': 'Communication Hub',
  '/communication-hub/inbox': 'Inbox',
  '/communication-hub/chat': 'Chat',
  '/communication-hub/broadcasts': 'Broadcasts',
  '/communication-hub/emergency': 'Emergency Center',
  '/communication-hub/calendar': 'Calendar',
  '/communication-hub/analytics': 'Communication Analytics',
  '/communication-hub/manager': 'Manager Dashboard',
  '/communication-settings': 'Communication Settings',
  '/settings/profile': 'Profile',
  '/notifications': 'Notifications',
  '/sla': 'SLA',
  '/templates': 'Templates',
  '/queue': 'Queue',
  '/organization': 'Organization',
  '/department': 'Department',
};

export default function DashboardLayoutRoute({ children }: { children: ReactNode }) {
  const pathname = usePathname();
  const segments = pathname.split('/').filter(Boolean);
  const crumbs = segments.map((seg, i) => {
    const path = '/' + segments.slice(0, i + 1).join('/');
    return { label: PATH_LABELS[path] ?? decodeURIComponent(seg), href: i < segments.length - 1 ? path : undefined };
  });

  return (
    <ProtectedRoute>
      <DashboardNav>
        <div className="mx-auto max-w-6xl space-y-6">
          <Breadcrumbs items={crumbs} />
          {children}
        </div>
      </DashboardNav>
    </ProtectedRoute>
  );
}
