-- 0013_ai_compliance_copilot.sql
-- AI Compliance Copilot & Sprint 5B AI Audit Assistant
--
-- Adds tables for:
--   * ai_conversations     — conversation metadata (title, pinned, tags, etc.)
--   * ai_documents         — uploaded documents for Document AI
--   * ai_policies          — generated policies with versioning + approval workflow
--   * ai_audit_assistants  — AI audit assistant sessions
--   * ai_audit_checklists  — AI-generated checklists
--   * ai_audit_findings    — AI-generated findings
--   * ai_audit_interviews  — AI interview assistance sessions

-- ---------------------------------------------------------------------------
-- Conversations
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_conversations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  title TEXT NOT NULL DEFAULT 'New conversation',
  pinned BOOLEAN NOT NULL DEFAULT FALSE,
  tags TEXT[] NOT NULL DEFAULT '{}',
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_conversations_org ON ai_conversations(organization_id);
CREATE INDEX IF NOT EXISTS idx_ai_conversations_user ON ai_conversations(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_conversations_pinned ON ai_conversations(pinned) WHERE pinned = TRUE;

-- ---------------------------------------------------------------------------
-- Documents (uploaded for Document AI)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  uploaded_by UUID REFERENCES users(id) ON DELETE SET NULL,
  filename TEXT NOT NULL,
  content_type TEXT NOT NULL,
  size_bytes INT NOT NULL DEFAULT 0,
  extracted_text TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'uploaded',  -- uploaded | processing | processed | failed
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_documents_org ON ai_documents(organization_id);
CREATE INDEX IF NOT EXISTS idx_ai_documents_status ON ai_documents(status);

-- ---------------------------------------------------------------------------
-- Policies (generated by Policy Generator)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_policies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  type TEXT NOT NULL,  -- child_labour | forced_labour | health_safety | environmental | human_rights | anti_harassment | supplier_code_of_conduct | ethics
  content TEXT NOT NULL,
  version INT NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'draft',  -- draft | pending_approval | approved | rejected | archived
  approved_by UUID REFERENCES users(id) ON DELETE SET NULL,
  approved_at TIMESTAMPTZ,
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_policies_org ON ai_policies(organization_id);
CREATE INDEX IF NOT EXISTS idx_ai_policies_type ON ai_policies(type);
CREATE INDEX IF NOT EXISTS idx_ai_policies_status ON ai_policies(status);

-- ---------------------------------------------------------------------------
-- AI Audit Assistant sessions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_audit_assistants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  audit_id UUID REFERENCES audits(id) ON DELETE CASCADE,
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  mode TEXT NOT NULL DEFAULT 'planner',  -- planner | checklist | document_review | interview | findings | report
  status TEXT NOT NULL DEFAULT 'active',  -- active | completed | archived
  context JSONB NOT NULL DEFAULT '{}'::jsonb,
  result JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_audit_assistants_org ON ai_audit_assistants(organization_id);
CREATE INDEX IF NOT EXISTS idx_ai_audit_assistants_audit ON ai_audit_assistants(audit_id);
CREATE INDEX IF NOT EXISTS idx_ai_audit_assistants_mode ON ai_audit_assistants(mode);

-- ---------------------------------------------------------------------------
-- AI-generated checklists
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_audit_checklists (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  assistant_id UUID NOT NULL REFERENCES ai_audit_assistants(id) ON DELETE CASCADE,
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_audit_checklists_assistant ON ai_audit_checklists(assistant_id);
CREATE INDEX IF NOT EXISTS idx_ai_audit_checklists_org ON ai_audit_checklists(organization_id);

-- ---------------------------------------------------------------------------
-- AI-generated findings
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_audit_findings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  assistant_id UUID NOT NULL REFERENCES ai_audit_assistants(id) ON DELETE CASCADE,
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  severity TEXT NOT NULL DEFAULT 'medium',
  category TEXT,
  recommendation TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_audit_findings_assistant ON ai_audit_findings(assistant_id);
CREATE INDEX IF NOT EXISTS idx_ai_audit_findings_org ON ai_audit_findings(organization_id);

-- ---------------------------------------------------------------------------
-- AI interview assistance sessions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_audit_interviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  assistant_id UUID NOT NULL REFERENCES ai_audit_assistants(id) ON DELETE CASCADE,
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  question TEXT NOT NULL,
  response TEXT,
  context JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_audit_interviews_assistant ON ai_audit_interviews(assistant_id);
CREATE INDEX IF NOT EXISTS idx_ai_audit_interviews_org ON ai_audit_interviews(organization_id);
